label Kaori2:
    scene white with Dissolve(.2)
    scene chapter_screen_1 with Dissolve(.2)
    show logo with Dissolve(.5):
        xalign .5
        yalign .6
        xpos .3
        ypos .5
        zoom .8
    $ renpy.pause(1, hard=True)
    show text "{size=40}{color=#3a47a6}Chapter Four \n{size=64}The Game Plan" at chaptertitlespot with Dissolve(1.0)
    $ renpy.pause(3, hard=True)
    scene courtyard empty with dissolve
    play music audio.Kaoritheme fadein (1.0)
    "After saying our goodbyes for the day, I head over to where the person in the letter wants to meet me."
    "Now that I'm thinking about it more, there's a pit of uncertainty forming in my gut."
    "Could someone I know have had a secret crush on me this whole time?"
    "Or even someone I've interacted with recently?"
    "I take the note out and look at it again."
    show Suzuki u speaking p1 at rightoffset with moveinright
    Suzuki "Hey, big guy!"
    Hiroya "Ack!"
    Suzuki u happy p1 "How're things, man? Passing all your tests? Getting the grades? {i}Getting the girls?{/i}"
    "He jogs over, flashing me his best used-car-salesman smirk."
    Hiroya "Get lost. I'm busy and you'll ruin the atmosphere."
    Suzuki u shouting p2 "What?! But I've been here waiting forever, you jerk!" with dissolve
    Suzuki "How long does it take you to read a simple letter?"
    Hiroya "..."
    Hiroya "You're dead."
    Suzuki u tough p1 "Hey man, I told ya we had to keep the mission under wraps. Besides, it worked didn't it?"
    Suzuki u tough p1 "Anyway! Pleasantries aside, let's get down to brass tacks!"
    Hiroya "Oh boy, my favourite."
    Suzuki u confident p2 "Alright Hiroya. I hope you're ready for this. I'm gonna make you an offer you {i}can't refuse!{/i}"
    Hiroya "Ohhh, we'll see about that."
    show Suzuki u happy p2
    "Suzuki was already snickering to himself. I was getting a bad feeling about all of this."
    "The dude was yammering on like a shonen hero or something."
    "Eh. I shouldn't worry about this too much. If he asks me to do something illegal, I'll bail."
    "And Miyu says he's been working with the school prez, so it's probably all fine. I'm sure this entire subplot will be grounded and sensible."
    "My eyes drifted over cautiously as Suzuki reached into his pocket."
    Suzuki "Awright, get a load of this!"
    #sfx swoosh
    Suzuki u vhappy p2 "Da da da daaaaa! A free ticket to the baseball game this afternoon~"
    Hiroya "What."
    Suzuki "We're having an exhibition game with our {i}hated rivals{/i} from Sakuranoki. It's gonna be hype!"
    Hiroya "I don't get it. The baseball game? Where's my sandwich?"
    Suzuki u tough p1 "Huh? What're you sayin'? This is way better than roast beef! Sugawara is the best place to see the stars of tomorrow in action today!"
    Suzuki u confident p1 "Like me! Suzuki Kisaragi, star athlete!"
    Hiroya "I'm going home."
    Suzuki u frown p1 "Aww, don't make me beg here. We can't have empty stands for our first big game of the season, y'know?"
    Hiroya "So you just want me to fill a seat then."
    "For some reason, this all sounded a bit too straightforward. I figured he'd want me to do something skeevier."
    "Like beat up a kid for him. Or rob a bank. Or burn pirated anime on a disk for him."
    Hiroya "I don't know, I hear the baseball team's been pretty lousy this year."
    Hiroya "But, uh, I don't really see a problem. I guess I'll check it out. There's nothing else to do around here anyway."
    Suzuki u vhappy p2 "Alright! It's gonna be some of the toughest, grittiest, sweatiest, hard-hittingest baseball you ever saw!"
    "He flexed his rotator cuff, striking a tough pose. I don't know who he was trying to impress."
    "I'm not much of a baseball guy, but I got the impression that if I admitted that, I'd break his fragile heart."
    Suzuki "Okay, I gotta jet. Got some running around to do 'fore the big game."
    Suzuki u happy p2 "Catch me after the game! I'm sure that'll be a great time for an autograph, eh?"
    Hiroya "I mean, I'll consider it, but I'd rather have another sandwich."

    Suzuki u tough p2 "Pfft! Funny guy. You're funny."
    hide Suzuki with moveoutright
    "With a flourish, Suzuki was off, jogging towards in the direction of the gym."
    "I shrugged, taking the moment to glance down at my ticket."
    Hiroya "'VIP ticket', huh? What's that about?"
    "I flip the ticket around, reading both sides. A few key words jump out at me."
    Hiroya "Free dinner? Damn, why didn't he mention that earlier? That's all he had to say to get me to come."
    "Pocketing the ticket, a bit more optimistic about today's outlook, I head over to the baseball field."

    scene baseball field with squares
    play music Jazz fadein 1.0
    "The stands are slowly filling up. I guess Suzuki ended up doing a ton of footwork getting the tickets out to people."
    "There's quite a buzz around the dugout as well. This might even be a fun game after all."
    Hiroya "I should find my seat. Before someone tries to take it or something."
    "Feeling oddly possessive, I cross-reference my ticket with the rows available."
    "Huh. Doesn't match up with the standard bleachers. Where the hell do I sit?"
    "I take another look around, getting a feel for the grounds. There's a tent set up next to the bleachers."
    "There's a sign posted near the front."
    Hiroya "Oh. VIP. Well that was easy. Guess I'll head over in that direction."
    Hiroya "{i}Whoa.{/i}"
    "Damn, this place is decked out. The tent is dominated by two leather recliner chairs. They looked more at home in my dad's man cave than out on the field!"
    "And there's a cooler nearby too."
    "I hurry over with a skip to my step, flopping into the nearer of the two chairs."
    "My busy eyes darted back and forth, trying to take everything in."
    Hiroya "What's this, a control panel? Oh man, does this thing give {i}massages!?{/i}"
    #sfx whir
    "By pushing a few buttons, I was able to confirm that theory, the backside of the chair rumbling into motion."
    Hiroya "Ohhhh yeaaaah, the absolute peak of luxury. They're gonna have to tear me from this thing, cuz I ain't giving it back~"
    #variable namechange to something like Posh Girl or something
    #oh gosh theres got to be some way we can get a CG of this scene
    play music audio.izumitheme fadein (1.0)
    show Shizuka u speaking at center with moveinbottom
    "Posh Girl" "Good afternoon."
    Hiroya "Wah!"
    "I was jostled out of my zen experience by a girl's voice. And she was dangerously close."
    "In fact, she was seated in the recliner next to me. She was staring at me, her face a mixture of confusion and judgment."

    Hiroya "Oh hey, uh, when'd you get here?"
    "Posh Girl" "Just now, actually. I hope you weren't in the middle of something?"
    Hiroya "Uh, no, not at all, lemme just... agh, how do I stop this thing... {i}does{/i} it stop?"
    "With a shrug, I lean forward to get a better look at the girl next to me."
    show Shizuka u neutral with dissolve
    Hiroya "There we go."
    "Posh Girl" "I suppose this means you have a ticket as well, yes?"
    Hiroya "Oh yeah, for sure. Check it out."
    "I flashed it before her with a quick flick of the wrist. She gave it a look, and nodded."
    "Posh Girl" "Hiroya...Tachibana?"
    Hiroya "That's me. Got it from the team captain."
    show Shizuka u happy with dissolve
    "Posh Girl" "Ohhh, I see. I was a little surprised, I was expecting to meet someone else here."
    "Posh Girl" "Still, it's a pleasure to meet your acquaintance. My name is Shizuka Endo."
    "Shizuka Endo..."
    "Her uniform was striking—very nontraditional, and definitely not from this school."
    Hiroya "Oh right, Suzuki was talking about you earlier."
    Shizuka u questioning "Was he now?"
    "Shizuka queried with an inquisitive tilt of her head."
    Hiroya "A little bit. Something about, uh... n-nevermind that."
    "The words 'dastardly plan' came to me, but I don't think Shizuka would appreciate hearing secondhand gossip about her. She seemed pretty polite."
    "Maybe I should deflect this somehow. Shizuka was looking at me funny."

    menu:
        "Ask about the free dinner.":
            jump shizukadinner
        "Talk about the game.":
            jump shizukasport
        "Ask about her uniform.":
            jump shizukauniform

    label shizukadinner:
        Hiroya "You're up for dinner later, right?"
        Shizuka u mad "!"
        Hiroya "I-I mean, the free dinner. That they, uh, the ticket, it says. You see."
        show Shizuka u questioning with dissolve
        "I wave the other side of my ticket. She silently examines it, her cheeks flushed, before she blinks."
        Shizuka u speaking "Oh! Ah, yes, I, I understand now!"
        Hiroya "Sh-sheesh, I don't wanna give you the wrong impression of me."
        Shizuka u confident "No no, it's fine, it's fine. A humorous misunderstanding, that's all."
        "She seemed find the situation amusing enough. Hopefully she didn't take me for some horndog. I don't work {i}that{/i} quickly on girls."
        "I tug at my collar, trying to wriggle out of that situation."
        Hiroya "Y-yeah, honestly, I'm more excited for the free food than the game itself."
        Shizuka u neutral "Ah, is that so? Rather much the opposite for me."
        Hiroya "Mm."
        "For a moment there, she looked disappointed. Her eyes drifted to the side."
        jump s2kaorimerge

    label shizukasport:
        Hiroya "...About how pumped he was for today's game!"
        Shizuka u happy "Ohh, I see. That's a relief. I'm excited for this game myself."
        Shizuka "Do you attend these games often? I'm surprised by the amenities this school offers."
        Hiroya "Uh, not really. This is my first."
        Shizuka "Ah, really? This must be quite exciting for you, then!"
        Hiroya "Sure."
        "I didn't have the heart to tell her I was in this for the free food. Her eyes lit right up."
        Shizuka "Well then, for both of our schools, I hope this turns out to be a good game. I've been looking forward to it!"
        Shizuka u speaking "Sakuranoki has a lot to learn from Sugawara in that area, but I feel our team's matured a lot since the previous season."
        "She spoke with pride, though her tone was soft. I was just surprised that Suzuki wasn't talking out of his ass earlier."
        Shizuka u confident "Ah, this is your first game. I can help point out what's happening, if that's alright with you?"
        Hiroya "Really? I, uh, sure!"
        "Again, she had such a relaxed, yet earnest approach. It was disarming as heck."
        jump s2kaorimerge

    label shizukauniform:
        Hiroya "So, uh, based on the uniform you're wearing, I guess you aren't from around here?"
        Shizuka u speaking "No, not from this school. I'm a representative of Sakuranoki."
        Hiroya "Ohhhh. The bad guys."
        Shizuka u questioning "...I beg your pardon?"
        Hiroya "N-not literally! Just... that's something that Suzuki said."
        Shizuka u neutral "Oh. I see. You two know each other?"
        Hiroya "Uh, sort of."
        Shizuka u speaking "Ahh. Now everything's clear now."
        "Shizuka seemed to relax"
        Shizuka u confident  "If it's not too much trouble, maybe you could help me? I would like his autograph while I'm visiting Sugawara."
        Hiroya "Wh- seriously? Aren't you here to root for your own team?"
        Shizuka u neutral "Mmhmhm, I prefer to consider myself an impartial observer."
        Shizuka "And even with school lines drawn as they are, I can hardly deny his aptitude and skill."
        Hiroya "Huh, I just figured he was making stuff up half of the time."
        "Well, shows what I know about baseball."
        jump s2kaorimerge

    label s2kaorimerge:
    Shizuka u speaking "It's certainly nice to get away from my responsibilities for a bit and take in a ball game."
    Hiroya "Oh yeah, you're the student council president over there as well?"
    Shizuka "That's right. It gets stressful at times, but I feel I've been able to do good by our school."
    Shizuka "Ah, my apologies, I don't want to come off as a braggart..."
    Hiroya "Nah, it's okay. We gotta take pride in something, right?"
    Shizuka "Oh, very true. Sugawara has its strong pedigree in the athletics, of course."
    Shizuka u confident "Including the baseball team! Going 16-0 last season is quite a feat."
    Shizuka "Part of me wishes I could come out to visit to attend more games. Ah, {i}c'est la vie.{/i}"
    Hiroya "Be careful what you say. High praise like that and people'll think you're a Sugawara superfan."
    Shizuka u neutral "W-well, I mean, of course I'm proud of {i}our{/i} team as well."
    Shizuka "I prefer to enjoy baseball as a neutral spectator. To enjoy the thrill of the game without the bias of team favoritism."
    Shizuka "I hope that doesn't sound pretentious or anything."
    Hiroya "Pretentious? Nah. I-I mean, a little bit, but..."
    Hiroya "...But everyone's gotta have a hobby, I guess."
    Shizuka u happy "That's a relief. I get too many raised eyebrows about this sort of thing."

    #gonna hit up some baseball nuts for inspiration

    Shizuka u speaking "Besides that, baseball is, well, it can be more cerebral. It's kind of like chess? There's a lot of microinteractions at play."
    Shizuka "It's just... in my opinion, there's hardly a better feeling than witnessing a duel between the batter and the pitcher."
    Shizuka "Or claiming the lead in a late inning. Or the perfect elegance of a curveball."
    Hiroya "Heh. If you get this excited before the game, I'm not sure how to feel about what might happen {i}during{/i} the game."
    Shizuka "Ah, well, I-I think I got a lot of this enthusiasm from my father."
    Shizuka u happy "When I was little, we'd travel overseas to America for his business."
    Shizuka "We'd try to catch the local games whenever we could."
    Shizuka "They play on a whole different level over there, but our boys at home are catching up too."
    Hiroya "No kiddin'. Maybe Suzuki'll end up with the big leagues soon."
    Shizuka "Maybe! I've heard some good things about his play, but it's been a while since I've seen him play."
    Hiroya "Seriously? I kinda figured he was inflating his ego a bit."
    Shizuka u neutral "Ah, no. I know our pitcher had a few hiccups facing off against his swing."
    Shizuka "But this year will be different. Poor fellow was only a freshman, after all."
    Hiroya "Mm, that's rough."
    hide Shizuka with dissolve
    "For a second, my eyes wander, scanning the diamond. Aside from the odd student athlete mulling about during pre-game warmups, there wasn't a ton to see."
    "In the corner of my eye, I spotted a familiar face approaching our tent."

    "It's Kaori."
    Shizuka "Ah, Kaori! Good to see you again."
    "Shizuka was the one to break the silence, straightening her back to address her."
    "Her words were formal, and perhaps a little stiff. Maybe Kaori had that effect on people."
    Kaori "Shizuka."
    "Kaori's eyes darted between the two of us, before settling on me."
    show Kaori u glaring p1 at center with dissolve:
        xflip
    Kaori u cool p1 "What are {i}you{/i} doing here?"
    Hiroya "Uh. It's nice to see you too, Kaori. Feels like it's been forever."
    Kaori u confused p1 "It's been half an hour."
    Kaori "..."
    "Kaori glanced over to Shizuka. She was getting a strange look from her, but Shizuka didn't interject."
    #voice: strained
    Kaori u concerned p1 "Nngh... are you {i}enjoying{/i} your school life at Sugawara to the fullest?"
    Hiroya "It's not bad. Wish they'd install these loungers in every classroom though, it'd really help me get the most out of study time."
    Kaori u cool p1 "You're joking."
    Shizuka "Hmmm. Personalizing your surroundings is the best way to optimize a studying environment."
    Kaori u shout p1 "Ugh, don't indulge his insane ideas!"
    Kaori u frustrated p1 "Aaaand we lost her. She's already considering it."
    "Kaori heaved a weary sigh, folding her arms."
    Kaori u frustrated p2 "It's fine if you want to watch the game, but you'll have to watch from the bleachers. This section is VIPs only."
    Hiroya "But I am a VIP."
    Kaori u glaring p2 "No you aren't. I didn't invite you."
    Hiroya "Suzuki did."
    Hiroya "And he got me this ticket, see?"
    "I flash my ticket for Kaori. She squints her eyes to look it over."
    Kaori u shocked p2 "S-seriously? Why do you even have-"
    Kaori u shout p2 "Ugh, Suzuki, you {i}idiot{/i}."
    "Kaori muttered under her breath. Shizuka didn't seem to notice, she was too distracted by the exercises out on the diamond."
    Kaori u frustrated p1"Alright, Hiroya, could I get a word with you? Over there, in the corner?"
    Hiroya "See, I wouldn't mind, but I'm still working out all the settings on this chair, so I'm a little busy-"
    show Kaori u confused p1
    #sfx shove
    Hiroya "Wh-wh-whoa-kay, s-settle down big girl!"

    scene sky with blinds
    #find a better background for this
    "Kaori grabs my arm without a word, hauling my ass from my velvety throne and dragging me away from the tent."
    "She had uncanny amounts of strength."
    "She nearly threw me to the ground, but I managed to catch my footing."

    Hiroya "H-hey, easy there, I'm delicate!"
    Kaori "What the hell is your problem!?"
    Hiroya "{i}My problem!?{/i} You just dragged me over here in a vicegrip!"
    Kaori "Look, I don't know what your game is here, but I'm sure as hell going to find out!"
    Kaori "Following me in the courtyard was one thing, but now I spot you with {i}Shizuka{/i} of all people?"
    Hiroya "It's my assigned seat! It's not weird at all!"
    Kaori "I can put a name to every face of every student at this school..."
    Kaori "...And yet you're the only one whose name, whose presence, came out of nowhere. Now why is that?"
    Kaori "And then there was the thing in the student council room..."
    Hiroya "Do you really need to see my ticket a second time? That's my seat."
    Hiroya "And I've grown rather attached to it, so if we could just go back and pretend this conversation never happened-"
    Kaori "God, you're stupid. Maybe you really are that oblivious."
    "Like flipping a switch, she eased off with a heavy sigh."
    Kaori "It's my seat."
    Hiroya "Do you have a ticket for it?"
    Kaori "Of course I don't! Suzuki gave you my ticket!"
    Kaori "And he mixed it up with the handouts! Ugh, is he colorblind?"
    Hiroya "I dunno, but it sounds an awful lot like only one of us has the rightful claim to the throne."
    Kaori "You don't realize the forces with which you're meddling with!"
    "Kaori was giving me the dirtiest look imaginable, but it was clear that she was trying to keep her voice only slightly above a raspy whisper."
    Kaori "..."
    Hiroya "If you got nothing else to say, I'll just go back to my seat-"
    Kaori "You can't! I {i}need{/i} that seat!"
    Kaori "Just - just listen to me, okay? You truly don't understand the forces at play here."
    Hiroya "It's a seat at a baseball game. You can reel it back a little."
    Kaori "It's the best way for me to keep an eye on Shizuka. So I can properly gather intel on her. Get inside her head."
    Kaori "This is no mere baseball game. This is a powerplay, and I intend to come out on top!"
    Hiroya "Can't you just leave the dick-measuring contest to Suzuki and the boys, though? That's all anyone's paying attention to anyway."
    Kaori "If the student council president submitted to some random student, it reflects exceptionally poorly on me."
    Kaori "She's a conniving sort, she wouldn't forget. It would be a slight against my honor - Sugawara's honor!"
    Kaori "Look, if we make the trade, I'll owe you a favor, alright? Let's just make this discreet."
    Hiroya "A favor?"
    "I still wasn't sure what she was getting at, but she really wanted that seat. Like, maybe she wanted it too badly."
    "Still, I'm not altogether too privy to getting pushed around."
    Hiroya "..."
    Hiroya "Alright, whatever. You can take the dumb ticket."
    Kaori "Haah, thank god. You're catching on to how these things work."
    Hiroya "Not really. It's just clear to me that you want it more badly than I do."
    Hiroya "But I still want that free dinner the ticket promised. I was hedging my entire evening plans on it."
    Kaori "Yes, yes, of course. Leaving you out of that would make Suzuki rather upset."
    Kaori "I'll even find you another seat in the VIP tent, so you can enjoy the amenities~"
    Hiroya "I could go for some melon soda, if that's in the cooler."
    Kaori "Yes, obviously. Now come on. If we dawdle, Shizuka will get suspicious."
    Hiroya "Really? She's kind of just watching the players."
    Kaori "It's a front. She's taking plenty of notes on me, and I can't look like a fool in front of her."
    Hiroya "She seems alright to me, but whatever you say."
    scene baseball field with squares
    "The two of us hurried back to the tent."
    "Kaori had her solution in mind: my luxurious leather recliner was downgraded to a cushion on top of the cooler."
    "Whatever. It wasn't the VIP throne I was promised, but at least I got first dibs on all the drinks."
    "Dinner couldn't come soon enough."
    "Shizuka had a notebook on her lap, scribbling in it intently."
    Hiroya "Did you bring your homework to a baseball game?"
    show Shizuka u speaking  at rightoffset with dissolve
    Shizuka "..."
    Shizuka "Huh?"
    "Shizuka took a moment to realize she was being addressed. It then took her another moment to process the question."
    Shizuka u happy "Oh! This? This isn't... it's just a scorecard. Notes I'm taking, just getting it ready."
    Shizuka "I was going to send these to the journalism club. Ah, Kaori, would you like a copy as well?"
    show Kaori u cool p1 at leftoffset with dissolve
    Kaori "Pass. There isn't a student in this school that isn't aware of the exploits of our baseball team."
    Shizuka u speaking "Ah, I presumed that your school paper would have use of it. My mistake."
    "Looking a little deflated, Shizuka lowered her pen with a sigh. It looked like her template was ready."
    hide Shizuka with dissolve
    hide Kaori with dissolve
    Hiroya "Oh hey, the game's starting."
    "Sugawara was up to plate."
    Hiroya "I don't see Suzuki, though."
    Shizuka "Ah, I got the batting order here... he's fourth up to bat."
    Hiroya "Really? So much for being the prodigal talent."
    Shizuka "Generally, you want your star player to swing after a few bases are loaded."
    Shizuka "That way, they can shoot for a chance at a multi-run homer."
    "Shizuka explained with a gentle smile."
    Kaori "You've been doing your homework on Sugawara, I see."
    Shizuka "Well, no, it... it's pretty simple strategy. Baseball strategy."
    Shizuka "I just hope that Kaz is up to the task."
    "Her eyes drifted to the pitching mound anxiously. She leaned forward in her seat, watching his every movement."
    "Man, I feel bad for that guy. Must be a ton of pressure, being under the eyes of an entire school."
    #sfx pitch
    Kaori "Ah!"
    #sfx pitch
    Hiroya "H-holy..."
    #sfx pitch
    Shizuka "Nice! That's a strike!"
    Hiroya "Seriously? That was so fast!"
    Shizuka "Kaz was working on his fastball. I'm really happy, he looks so much more confident with it this year."
    Shizuka "Ah! He did it again!"
    Hiroya "The hell?"
    Kaori "Tch. It's a fluke at best."
    Shizuka "Well, confidence in your students is always a plus. I'm rather happy with Kaz's growth so far."
    Kaori "Hmph."
    "Before long, Sakuranoki's pitcher struck out all of our batters. Sugawara was out on the field now."
    "Now I see Suzuki! He's near the first base. I wave to him to try and get his attention, but he doesn't notice."
    Hiroya "Alright, whatever."
    Kaori "Don't try to distract him. He's trying to focus."
    Kaori "Athletes need to be in the proper mindset to perform at their best."
    Shizuka "Very true. Ah, speaking of which..."
    Shizuka "Kaori, are you still working on your archery skills?"
    Kaori "..."
    Shizuka "It would be an honor to have you come to Sakuranoki in the spring for our tournament-"
    Kaori "FOUL!"
    "Kaori hollered out a warning, before sticking her hand out."
    #sfx thwack
    "Kaori throws her hand out, catching the ball mere inches from Shizuka's face."
    Shizuka "!"
    Hiroya "Damn. Nice reflexes!"
    Kaori "Nn."
    Shizuka "Th-that was most impressive! That ball was flying right towards my head."
    Shizuka "I could've been sent to the nurse's! Thank you for watching out for me!"
    Kaori "I was doing what now?"
    "Kaori blinked, before wincing slightly."
    Hiroya "Is your hand okay? Do you need ice for that? You weren't even wearing a glove."
    Kaori "Yeah, I'll be fine."
    "She uttered through grit teeth. The corners of her eyes sparkled with tears of pain."
    "With a breath, she relaxed, plopping the ball to the ground. Shizuka's eyes followed it as it rolled."
    Shizuka "I might take this back home, if you don't mind. It'd make for a nice memento!"
    Kaori "Suit yourself. It's just another freebie to add to the pile."
    "Kaori flexed her palm a few more times. Why was she being so cold?"
    Kaori "I don't know what kind of result you're expecting. Sugawara fields the top baseball team in the province!"
    Shizuka "Well, that might've been true last year, but..."
    Shizuka "Mm. I don't believe I really expect anything. I only hope for a good game."
    Kaori "Nrgh... you could be a {i}little{/i} competitive."

    #sfx homerun hit

    "Kaori's disappointed muttering was interrupted by the loud crack of a bat. It echoed through the field."

    Shizuka "Ohhh! Would you look at that! I say that's a... a..."
    "Shizuka trailed off, following the trajectory of the ball. Her eyes lit up as it sailed over a fence towards the back."
    Shizuka "It's a homerun! Yes!"
    Hiroya "Whoa. Sakura's got some sluggers up to bat."
    Kaori "Wh-whatever! A broken clock's correct twice a day-"

    #sfx homerun hit

    "A familiar splitting sound followed through."
    Shizuka "Oooh, that's gotta be a double hitter!"
    Kaori "O-oh come on, at least let me finish!"
    "The Sugawara pitcher didn't looked rattled from the outset, but his fastballs weren't looking as crisp as Sakura's guy. Must've been a hard position to be in."
    #sfx bomerun hit
    "That didn't distract from the fact that the bats were hitting everything he had to dish out, running up the score in the process."
    "I counted at least four home runs. There wasn't anything Suzuki could do, but..."
    "Boy was he trying. He was scrambling all over the field to catch any balls that got popped up."
    Hiroya "Isn't he supposed to be covering the first base?"
    Shizuka "Yes. I'm surprised at the distance he's able to cover."
    Shizuka "He's really trying to carry the entire team... it's really quite admirable."
    Kaori "COME ON SUZUKI, PUT SOME BACK INTO IT!"
    "Almost in response, Suzuki managed to catch a fly ball."
    Kaori "YES! Finally, the bleeding can stop."
    "I sneak a cursory glance to the scoreboard. Sakuranoki was up 7-0."
    Hiroya "Holy crap, isn't that a little lopsided? I thought Sugawara was hot shit!"
    Shizuka "Well, I have one theory to explain this discrepancy."
    "Shizuka frowned to herself. It didn't seem like she was enjoying the lopsided result either."
    Shizuka "If I recall correctly, many of Sugawara's most important players were part of the graduating class."
    Shizuka "And I'm seeing a fair number of newer players. Of course there's going to be some growing pains."
    Hiroya "Newbies? You can tell?"
    Shizuka "Well, I... I did a bit of research, going into this."
    Kaori "Oh I know you did research."
    "Kaori shot Shizuka a suspicious look. Shizuka didn't seem to notice, however."
    Shizuka "Baseball's a bit of a thinking man's game. I like to be well-informed on the nuances."
    Shizuka "Oh, would you look at that. Sugawara's struck out again."
    Kaori "W-what!? I looked away for {i}five seconds{/i} and they up and-"
    Kaori "URGH!"
    Hiroya "Easy there, it's just a game. The boy's'll run it back."
    "My optimism ran a bit hollow, considering the sort of team we were up against, but Shizuka seemed to be supportive."
    Shizuka "And even if they don't, I'm sure this will be a valuable learning experience for both of our schools."
    Kaori "It's easy for you to say that when {i}your school{/i} can afford to co-opt the Olympic training grounds."

    "Needless to say, the situation did not improve. If anything, the Sakuranoki team was more determined to run up the score than ever."
    #sfx homerun hit
    "Honestly, I was losing track of the number of big hits they were making. And I stopped looking at the scoreboard at the 20-0 mark."
    "Ironically, Shizuka was the one suffering the most in all of this. In the corner of my eye, I could see her furiously scribbling notes just to keep up with all the incoming data."
    play music Early fadein 1.0
    Kaori "HEY! HEY! What are you DOING!?"
    Hiroya "Huh?"
    "Kaori shot up from her seat, her face red in anger. For a second, I thought this was the latest in a series of salty exclamations, but..."
    Hiroya "Is that a fight breaking out?"
    Shizuka "What!? A fight!? That's not-"
    Shizuka "O-oh my!"
    "Near the dugouts, Suzuki was squaring off in a five-to-one rumble, and his teammates were leaping in behind him."
    Hiroya "Is that legal?"
    Shizuka "Only in hockey... what's the meaning of this?"
    Kaori "Oh please! Don't pretend to act so innocent! You put them up to this, didn't you!?"
    Shizuka "What? You're insane, we have nothing to gain from antagonism. We're {i}winning.{/i}"
    Kaori "Oh, spare me the demure pretty girl act! I know your family's playbook!"
    Kaori "Picking a fight with a handpicked selection of goons, and you think that's supposed to intimidate us!?"
    Shizuka "Don't bring my family into this! Ugh, this is frustrating."
    Shizuka "I can see bickering with you is utterly pointless. I'm going down there to sort this mess out!"
    Kaori "Like hell you are! Not if I get there first!"
    Shizuka "Wh-hey! This isn't a race!"
    Shizuka "Sorry, Hiroya, we'll go sort out the players."
    Hiroya "Y-You do that. I figure between you and Kaori, you two'll have it settled."
    Shizuka "Thank you for understanding. Agh, this turned into such a mess..."
    "Shaking her head, Shizuka jogged behind Kaori."
    "Leaning over, I grab another drink. Better to leave the de-escalation process to the professionals. I didn't want to get too involved."
    if kaoriticket == True:
        "And besides, this was a good time to take my seat back. Yoink!"
    "Seeing Kaori in action was something else. She marched right into the thick of it and judo-threw the nearest player."
    "I winced at the impact. The motion was a bit too familiar, and the impact was deafening. At the least, it was enough to get the boys to stop squabbling."
    "It was hard to tell what was happening afterwards. Kaori took the Sugawara boys aside, and Shizuka the Sakuranoki boys, and..."
    "I couldn't make out what they were saying, but it probably wasn't very nice. Their words were being drowned by the murmur and cheers of the crowd."
    "The officiators stepped in from there, and the speakers crackled."

    "Announcer" "Attention students. This exhibition game between Sugawara Academy and Sakuranoki has concluded."
    "Announcer" "The officials have invoked the mercy rule in light of the brawl. Please leave through your nearest gate."
    Hiroya "Aww, seriously?"

    "I glance down to my leather chair. I probably wouldn't get a chance like this ever again."
    Hiroya "So long, big guy. I will never forget you..."
    "Rising from my seat, I reach for the ticket in my pocket."
    Hiroya "Huh. There's an address in here for where the dinner's at. Guess I can head over early."
    "I considered that, but I noticed that the crowd on the field was beginning to disperse. It looks like the teams were done squabbling..."
    "But Kaori and Shizuka were having an argument instead."
    scene sky with dissolve
    Shizuka "What a dreadful display! Are you ready to explain some of those {i}choice words{/i} your buffoons had to say?"
    Kaori "Are you blind!? Your cronies were the ones showboating! I saw your beloved Kaz throw the first punch!"
    Shizuka "Absolutely idiotic, why would our star pitcher risk his good hand on a pointless squabble?"
    Shizuka "This was a pathetic attempt to restore your pride. It's unbecoming of an elite school!"
    Kaori "You can't come here and tell me how we run things! We don't back down to goon tactics!"
    Hiroya "H-hey, um, girls? The game's over. Everyone's leaving. Maybe we can save this for another time?"
    Kaori "Nrgh, who asked for your opinion!?"
    Hiroya "I'm just saying, everyone's preeetty pissed off. Maybe this ain't the best time or place to be having this talk?"
    Shizuka "{i}Finally{/i}, someone from this school talks some sense. I'm in complete agreement."
    Shizuka "I can tell this outing has been an utter waste of my time. Farewell, Kaori."
    "Stiffly, Shizuka turned to walk away, towards the visiting team's dugout."
    Kaori "Yeah, keep running from the truth, you two-faced harlot!"
    Kaori "Ugh..."
    "Kaori massaged her face."
    Kaori "What the hell do you want?"
    Hiroya "I just wanted to make sure things were being resolved peacefully."
    Kaori "Oh just stuff it. I know you just came to get food."
    "Kaori rolled her eyes, folding her arms."
    Kaori "Fine. Kaori Chiba doesn't waver from her promises. We can head over with the rest of the team."
    Hiroya "Wait, the whole team?"
    Kaori "Duh? It was {i}supposed{/i} to be a celebratory dinner. To ring in our great victory over Sakuranoki..."
    "She snuck a glance to the lopsided scoreboard, heaving a sigh."
    Hiroya "Well, I mean... it {i}can{/i} be considered some kind of victory."
    Kaori "Shut up. It was a total flop. We even lost the brawl."
    Kaori "Just stay here. I'll fetch Suzuki. He's still getting iced for some bruises."
    Hiroya "Y-yeah, he was in the thick of it, huh."
    Kaori "His own damn fault he can't throw a good punch!"
    Kaori "Nrgh, it's fine. I'll just teach him a thing or two myself."
    Hiroya "D-don't put him through the ringer too hard."
    Kaori "Oh, he's a big boy. He can take it."
    Kaori "Just wait near the gates. We'll find you then."
    "With a scowl, Kaori turned towards the dugout. It looked like she was on the warpath now."
    "I had a hunch that this peptalk of hers was going to go on for quite a long time."
    "Shooting one last, forlorn glance to the cozy tent I was leaving behind, I move to vacate the grounds with the rest of the crowd."
    jump Kaori3



#########Deprecated Miyu scene. She discusses some of her basic association with Suzuki. Saved for future reference.
        # show Miyu u nervous with dissolve
        # pause(1)
        #
        # #drafts don't have honorifics right now because i am bad at them, edit later
        # Hiroya "Oh, crap, I just remembered, I should probably let you know. I ended up making some other afternoon plans."
        # Hiroya "I won't be able to hang out at all today."
        # Miyu u nervous "Oh, really? That's a little unexpected, um..."
        # Hiroya "Yeah, I already texted Akari with the heads up, so yeah."
        # Miyu u concentrating "Ah, I see. I guess I'm a little out of the loop, aha..."
        # Hiroya "You should look into getting a phone. It's the twenty-first century, times are changing."
        # Miyu u happy "Oh, I'm okay! I have a phone for emergencies!"
        # "Miyu fished into her backpack, pulling out what she called her personal phone."
        # Hiroya "The hell? It's like a brick."
        # Miyu "Well, yeah. It's dad's old Nokia. It still works great!"
        # Hiroya "Is that a black-and-white screen? It's so small, how can you read from it?"
        # Miyu u concentrating "Well, um, it handles phone calls fine, and that's all that matters."
        # Miyu u happy "N-nevermind that. Did you make a new friend?"
        # Hiroya "'New friend'? Uh, not sure, really."
        # Miyu u speaking "Huh. Did you finally get around to joining a school club?"
        # Hiroya "Nah. Too much of a commitment. They're for squares anyway."
        # #miyu pout
        # Miyu u concentrating "Hm."
        # Hiroya "I-I mean, I say that in the most flattering way possible. You, uh, do good work on the council!"
        # Miyu "I have a hard time believing you were trying to be flattering, Hiroya."
        # Hiroya "Well, like, who else but a square could handle the intense workload? It's a compliment, you see, because you..."
        # Hiroya "No one else can do the work you guys do and... uh..."
        # Miyu u speaking "Haa?"
        # Miyu u happy "It's okay. I'm sure you meant well enough."
        # "Even as she said this, she was giving me a pitiful look, like 'I know you're an idiot, but I am a merciful sort, and I forgive you. This time'."
        # "I feel like that's what Miyu meant to say, but she's too nice to be so backhanded."
        # Miyu "So what's this about then, if you don't mind me asking? Part-time work? Babysitting? Pagan rituals?"
        # Hiroya "Uh, no, not exactly. None of the above. I don't even know about that last one."
        # Hiroya "I owe this guy Suzuki a favor, so I'm gonna see what's that about."
        # Miyu u speaking "Suzuki? Oh, the baseball guy?"
        # Hiroya "Yeah, something something prodigal tour de force or something like that. You know him?"
        # Miyu u concentrating "N-not personally. I've just seen him hanging around Kaori a fair bit lately. Not super sure what that's about though."
        # Miyu u happy "Ah well. Don't mind me. You guys have fun, okay?"
        # Miyu "Who knows, he might ask you to join the baseball team! Wouldn't that be exciting?"
        # Hiroya "Doubt it. I'm not exactly the sporty type. And I don't think they need a designated hitter either."
        # Miyu u concentrating "You should take your extracurriculars more seriously, Hiroya. Stuff like that is good on a resume!"
        # Miyu "In a few years, we'll have to go out into the adult world. High school's the time to make a good impression!"
        # "Miyu was always so serious about her pursuits, and her lectures always came from a place of passion. It always shone through when she got really into something."
        # "It's hardly a surprise that she managed to get herself on the student council as Vice President. Most of the time she came off shy and reserved, but when she had something important to say, she could nail a rousing speech every time."
        # Hiroya "I mean, you're not {i}wrong{/i}, but..."
        # "I couldn't tip her off about my home situation yet. There were things I needed to sort out soon."
        # Hiroya "I need to focus on the present first before I can look ahead to the future, you know?"
        # Miyu u happy "Mm."
        # "Miyu didn't seem a hundred percent satisfied with that answer, giving me a questioning look."
        # Miyu u speaking "If you're sure. But don't let tomorrow sneak up on you either, okay Hiroya?"
        # Hiroya "Heh. Yes ma'am."
        # Hiroya "I need to mosey though. Suzuki's probably wondering where I'm at."
        # Miyu u happy "Aww. Okidoke. I won't hold you up any longer. Have fun!"
        # Hiroya "Yeah, you too."
