# This is the intro. When you press the start button, the game will begin here.
#used for testing purposes
#label testing:

label start:
    stop music fadeout (2.0)
    scene black with dissolve
    play music Spectre
    "In the most quiet part of the night, I walk up the steps to our dingy two-bedroom apartment."
    #sfx unlocking door, open
    "I pull the door open and step inside."
    scene apartment night with squares
    Hiroya "I'm back."
    "The smell of smoke hangs heavy in the air. My nose crincles in response."
    "The room is dark. A commercial plays on the TV in a low volume, a small collection of beer cans and ramen cups lay near the coffee table."
    "Among them is my father, hunched over the table, exhaustedly sucking at the filter of a cigarette."
    Hiroya "Dad..."
    "I call out again."
    Dad "Mm."
    "He stirrs."
    "I drop my schoolbag near the door and stroll over to the kitchen. I search the fridge for any ingredients I could possibly turn into dinner."
    "Let's see."
    "Condiments, some beer, a carton of milk."
    "No combination of ingredients that could ever comprise of a meal."
    "I'm almost starting to expect that."
    Hiroya "*sigh*"
    "I close the fridge and return to the living room."
    Hiroya "Give me some money. I'll go pick up some sandwiches."
    Dad "Hmph."
    "He takes the last drag from the cigarette and lets it out with a sigh."
    Dad "You see what's on the stove. Eat what we got."
    "I turn back to the kitchen. I see a bowl on the counter covered with a paper napkin."
    "I lift up the napkin with low expectations."
    "Inside, I find a clump of old, hard steamed rice."
    Hiroya "Hmm."
    "I replace the napkin and go back to the living room."

    Dad "They only want spry, young folk working anyway."
    "He points saying something to the television."
    "He reaches for another cigarette, only to find that the box is empty."
    "He glares down into the empty carton."
    Hiroya "Dad, give me some money. I'll go buy some sandwiches from the convenience store."
    "He tosses the carton aside and reaches into his pants pocket."
    "He pulls out another carton of cigarettes."
    Hiroya "Dad!"
    Dad "Do I look like I'm made of money?"
    "His voice is hoarse."
    Hiroya "...Just how much of your check did you spend on cigarettes?"
    Dad "I don't need my good-for-nothing son giving me shit about how I relax."
    Hiroya "It never changes with you, does it?"
    "I look at the mess he's made."
    Hiroya "We can't keep living like this."
    Hiroya "How long is it going to take for you to pull yourself together?"
    Dad "..."
    Dad "Don't preach at me, boy."
    Dad "Don't kids your age pick up part-time work? Try working 'til your knuckles bleed, you'll be bloody tired all the time too."
    Dad "You might even enjoy a good smoke."
    Dad "Now leave me the hell alone!"
    Hiroya "..."
    "This is how it's been since Mom left."
    "I turn and start towards my room."
    Dad "Parasite."
    Dad "That's all you are."
    Hiroya "..."
    Dad "If only I didn't have you sucking up my hard-earned wages...I wouldn't be in this mess."
    "I turn to leave him once again."
    Dad "Where're you going? I'm talking to you!"
    Hiroya "Whatever, old man."
    Hiroya "You know this kind of shit is exactly why Mom left you."
    Hiroya "You good-for-nothing pig."
    "I head for the door."
    #sfx cloth rustling (like a backpack being roughly grabbed/tugged at
    Hiroya "Hn!"
    "He grabs me from behind."
    Hiroya "Let go of me, asshole!"
    "I tug and pull with all my might. But he just won't give up."
    Hiroya "Let-LET GO OF ME-"
    #sfx whoosh
    "{b}WHOOSH!{/b}"
    #if we have a bg a screen shake for impact might be good
    #sfx impact
    "{b}THUD!{/b}"
    #sfx collapse on floor
    "I hit him."
    Dad "Ungh."
    "I turn around. He wipes a hand over his nose. A smear of fresh blood streaks over his face."
    "His eyes are no longer that of a tired salaryman. There was something else there now."
    "Something vicious."
    Hiroya "Urk!"
    "He grabs me by my shirt collar."
    Dad "Ah... pull a cheap shot on your old man..."
    "I try to wiggle out, but he's strong."
    "He's got me pressed against the wall."
    Dad "You got {i}no idea{/i} who you're dealing with, you mouthy little brat!"
    Dad "{b}I{/b} am the supporter of this house. I pay the bills!"
    Dad "You think you'd be anything without me, boy?"
    "I try to pull away. He doesn't let go."
    Hiroya "..."
    Dad "Answer me!"
    Hiroya "Anywhere but with you."
    #sfx dull hit
    "I kick forward with everything I have."
    Dad "Ah! Smarmy {i}prick!{/i}"
    #sfx swing
    "He reels back, dropping his grip on my shirt."
    "I grab my pack and make a break for the door."
    Dad "Where you going?"
    Dad "You running away or something? Gonna go live under the bridge, are you?"
    Hiroya "I'm leaving this crummy apartment behind. I'm leaving you behind."
    Dad "You're serious? What the Hell do you think you're doing?"
    Dad "Hiroya..."
    Dad "You know what, fine."
    Dad "Think you'll do that much better on your own? Well go on then."
    Dad "Get out of my house, you ungrateful punk."
    "I open the door and look out into the night."
    "This is it then. Time to leave the pig."
    Dad "Wait."
    "He calls from behind."
    Dad "Before you go..."
    "I begin to turn."
    "The last thing I see is his scarred knuckles making a beeline towards my face."
    scene black with vpunch
    play sound "sfx/heavy_bag_drop_dirt2.ogg"
    "..."
    "That fucker."
    "He shuts the door, leaving me alone in darkness."
    stop music fadeout 2.0
    $ renpy.pause (3, hard = True)
    scene black with fade
    jump chapter1
